config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    %w[name]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :set_book, only: [:edit, :update]

  def index
    @q = Book.ransack(params[:q])
    @books = @q.result(distinct: true)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to root_path, notice: "蔵書の登録が完了しました"
    else
      flash.now[:notice] = "蔵書の登録が失敗しました。もう一度やり直してください。"
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to root_url, notice: "蔵書の更新が完了しました。"
    else
      flash.now[:notice] = "蔵書の更新が失敗しました。もう一度やり直してください。"
      render :edit
    end
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:name, :author, :memo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for book do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :memo %>
  <%= f.text_field :memo %>

  <%= f.submit "登録する" %>
<% end %>

app/views/books/edit.html.erb
<%= notice %>

<%= render partial: "form", locals: {book: @book} %>

<%= link_to '戻る', root_path %>

app/views/books/index.html.erb
<%= notice %>

<h1>BookLog</h1>

<%= search_form_for(@q) do |f| %>
  <%= f.label :name_cont, "名称" %>
  <%= f.search_field :name_cont %>
  <%= f.submit   %>
<% end %>

<table>
  <tr>
    <th>書籍名</th>
    <th>著者名</th>
    <th>メモ・感想</th>
  </tr>
  <% @books.each do |book| %>
    <tr>
      <td><%= book.name %></td>
      <td><%= book.author %></td>
      <td><%= book.memo %></td>
      <td><%= link_to "編集", edit_book_path(book) %></td>
    </tr>
  <% end %>
</table>

<%= link_to "新しい書籍を登録する", new_book_path %>

app/views/books/new.html.erb
<%= notice %>

<%= render partial: "form", locals: {book: @book} %>

<%= link_to '戻る', root_path %>